stages:
  download_data:
    cmd: python src/download_data.py --competition ${download.competition} --dest_dir ${download.dest_dir}
    deps:
      - src/download_data.py
    params:
      - download.competition
      - download.dest_dir
    outs:
      - data/raw

  preprocess:
    cmd: python src/preprocess.py --input_path ${preprocess.input_path} --output_dir ${preprocess.output_dir} --model_dir ${preprocess.model_dir} --train_ratio ${preprocess.train_ratio} --top_k_missing ${preprocess.top_k_missing} --clip_percentile ${preprocess.clip_percentile} --cat_min_freq ${preprocess.cat_min_freq}
    deps:
      - src/preprocess.py
      - data/merged_train_data.csv
    params:
      - preprocess.input_path
      - preprocess.output_dir
      - preprocess.model_dir
      - preprocess.train_ratio
      - preprocess.top_k_missing
      - preprocess.clip_percentile
      - preprocess.cat_min_freq
    outs:
      - data/processed/train_preprocessed.parquet
      - data/processed/val_preprocessed.parquet
      - models/preprocessor_v1.pkl

  feature_engineering:
    cmd: python src/feature_engineering.py --train_input_path ${features.train_input_path} --val_input_path ${features.val_input_path} --output_dir ${features.output_dir} --pca_components ${features.pca_components} --target_col ${features.target_col}
    deps:
      - src/feature_engineering.py
      - data/processed/train_preprocessed.parquet
      - data/processed/val_preprocessed.parquet
    params:
      - features.train_input_path
      - features.val_input_path
      - features.output_dir
      - features.target_col
      - features.pca_components
      - features.use_pca
      - features.use_missing_flags
      - features.use_v_features
      - features.use_frequency_encoding
    outs:
      - data/featured/X_train.parquet
      - data/featured/y_train.parquet
      - data/featured/X_val.parquet
      - data/featured/y_val.parquet

  balance:
    cmd: python src/balancing.py --x_train_path ${balance.x_train_path} --y_train_path ${balance.y_train_path} --x_val_path ${balance.x_val_path} --y_val_path ${balance.y_val_path} --output_dir ${balance.output_dir} --metrics_path ${balance.metrics_path} --sampling_ratio ${balance.sampling_ratio} --save_method ${balance.save_method} --random_state ${balance.random_state}
    deps:
      - src/balancing.py
      - data/featured/X_train.parquet
      - data/featured/y_train.parquet
      - data/featured/X_val.parquet
      - data/featured/y_val.parquet
    params:
      - balance.x_train_path
      - balance.y_train_path
      - balance.x_val_path
      - balance.y_val_path
      - balance.output_dir
      - balance.metrics_path
      - balance.sampling_ratio
      - balance.save_method
      - balance.random_state
    outs:
      - data/balanced/X_train_rus.parquet
      - data/balanced/y_train_rus.parquet
    metrics:
      - metrics/balancing_metrics.json

  train:
    cmd: >-
      python src/train.py
      --x_train_path ${train.x_train_path}
      --y_train_path ${train.y_train_path}
      --x_val_path ${train.x_val_path}
      --y_val_path ${train.y_val_path}
      --model_path ${train.model_path}
      --metrics_path ${train.metrics_path}
      --enable_tuning
      --n_trials ${train.n_trials}
      --tune_models ${train.tune_models}
      --mlflow_experiment ${mlflow.experiment_name}
      --mlflow_run_name ${mlflow.run_name}
      --register_model_name ${mlflow.register_model_name}
    deps:
      - src/train.py
      - data/balanced/X_train_rus.parquet
      - data/balanced/y_train_rus.parquet
      - data/featured/X_val.parquet
      - data/featured/y_val.parquet
    params:
      - train.x_train_path
      - train.y_train_path
      - train.x_val_path
      - train.y_val_path
      - train.model_path
      - train.metrics_path
      - train.n_trials
      - train.tune_models
      - mlflow.experiment_name
      - mlflow.run_name
      - mlflow.register_model_name
    outs:
      - models/model.pkl
    metrics:
      - metrics/train_metrics.json
